### ISSUE TITLE
enableCEC not working

### ISSUE THREAD

**Issue by MarcoGos** [kkapitan/homebridge-homesung#7]
When I set enableCEC to true (without quotes / double quotes) I'm getting an error:

(I already installed the cec-tools via sudo apt-get install cec-tools)

Error: spawn cec-client ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
/homebridge/node_modules/node-cec/lib/node-cec.js:64
      return this.client.kill('SIGINT');
                         ^

TypeError: Cannot read property 'kill' of undefined
    at process.NodeCec.NodeCec.stop (/homebridge/node_modules/node-cec/lib/node-cec.js:64:26)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process.emit (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/source-map-support/source-map-support.js:461:21)
    at process.exit (internal/process.js:146:15)
    at printErrorAndExit (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/source-map-support/source-map-support.js:445:11)
    at process.emit (/usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/source-map-support/source-map-support.js:457:16)
    at process._fatalException (bootstrap_node.js:391:26)

Can you help out?

I'm using the homebridge in a docker RPi environment.
My Samsung TV is a UE48JU7000

**Comment by MarcoGos** [comment]
It looks like the cec-utils are not installed within the docker container which result in the error. I've installed homebridge without the docker container and now the cec-client works.
